services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - postgres
networks:
  postgres: