# Generated by Django 5.0.4 on 2024-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('about_me', models.TextField()),
                ('education', models.TextField()),
                ('education_files', models.FileField(blank=True, null=True, upload_to='education_files/')),
                ('work_experience', models.TextField()),
                ('desired_position', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
    ]
