# Generated by Django 5.0.4 on 2024-07-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='education_files/', verbose_name='Файл аттестата')),
            ],
            options={
                'verbose_name': 'Файл аттестата',
                'verbose_name_plural': 'Файлы аттестатов',
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='about_me',
            field=models.TextField(verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contacts',
            field=models.TextField(verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='desired_position',
            field=models.CharField(max_length=100, verbose_name='Желаемая должность'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(verbose_name='Образование'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education_files',
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_files',
            field=models.ManyToManyField(blank=True, to='resume.educationfile', verbose_name='Аттестаты (PDF)'),
        ),
    ]
